//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMgtSystem_authenticationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendance
    {
        public int AttendanceID { get; set; }
        public Nullable<int> studentID { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<bool> isPresent { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
    }
}
