//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMgtSystem_authenticationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudent()
        {
            this.tblAttendances = new HashSet<tblAttendance>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> totalMarks { get; set; }
        public string div { get; set; }
        public Nullable<int> CouserId { get; set; }
        public Nullable<int> RegId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendance> tblAttendances { get; set; }
        public virtual tblCours tblCours { get; set; }
        public virtual tblRegistration tblRegistration { get; set; }
    }
}
